# Generated by Django 4.2 on 2023-04-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=10)),
                ('job_type', models.CharField(max_length=25)),
                ('customer_order_ref', models.CharField(max_length=55)),
                ('order_date', models.DateField()),
                ('process_date', models.DateField()),
                ('order_value', models.IntegerField()),
                ('customer', models.CharField(max_length=55)),
                ('account_type', models.CharField(max_length=25)),
                ('doors_s', models.IntegerField(default=0)),
                ('doors_d', models.IntegerField(default=0)),
                ('order_req_by_date', models.DateField(blank=True, null=True)),
                ('handling_floor_plans', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_sent_for_approval', models.DateField(blank=True, max_length=25, null=True)),
                ('date_approval_recived', models.DateField(blank=True, max_length=25, null=True)),
                ('date_into_production', models.DateField(blank=True, max_length=25, null=True)),
                ('date_dispatch', models.DateField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bootstrap_colour_class', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tracker.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_history', to='tracker.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_notes', to='tracker.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_notes', to='tracker.projectnotes'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tracker.status'),
        ),
    ]
