# Generated by Django 4.2 on 2023-04-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_approval_recived',
            field=models.DateField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_dispatch',
            field=models.DateField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_into_production',
            field=models.DateField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_sent_for_approval',
            field=models.DateField(blank=True, max_length=25, null=True),
        ),
    ]
