# Generated by Django 4.2 on 2023-05-03 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_alter_project_project_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Project engineer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tracker.status'),
        ),
    ]
